[workspace]
authors = ["Vecko <36369090+VeckoTheGecko@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "python4lunch_cmip6gc"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2025.12.0,<2026"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.1,<3"
intake = ">=2.0.8,<3"
xmip = ">=0.7.2,<0.8"
xesmf = ">=0.6.0,<0.7"
jupyter = ">=1.1.1,<2"
intake-esm = ">=2025.12.12,<2026"
requests = ">=2.32.5,<3"
aiohttp = ">=3.13.3,<4"
gcsfs = ">=2025.10.0,<2027"
nc-time-axis = ">=1.4.1,<2"
