[workspace]
authors = ["Tim Hermans <timthjhermans@gmail.com>"]
channels = ["conda-forge"]
name = "python4lunch_cmip6gc"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
xesmf = ">=0.7"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.8,<4"
requests = ">=2.32.5,<3"
intake-esm = ">=2025.12.12,<2026"
xmip = ">=0.7.2,<0.8"
aiohttp = ">=3.13.3,<4"
gcsfs = ">=2025.10.0,<2026"
nc-time-axis = ">=1.4.1,<2"
